### ISSUE TITLE
Conda-Forge Package

### ISSUE THREAD

**Issue by snowman2** [MrMinimal64/timezonefinder#43]
I have not seen a package for timezonefinder on conda. More information about it can be found here https://www.continuum.io/downloads. I am in the process of making one on conda-forge and was wondering if @MrMinimal64 would like to be a maintainer of this as well?

Thanks!

**Comment by MrMinimal64** [comment]
Thanks for the notification! Unfortunately I am not really experienced with anaconda (conda-forge etc.) so go ahead for now. If any issues occur feel free to contact me. This package would enable easy installation with all the dependencies, right?
When you are done send me the link. Then I am going to check it out and place a link in the readme here.

**Comment by snowman2** [comment]
OK. It will definitely enable easy installation through conda. Although the installation will not be much better than pip, it enables other packages in conda-forge dependent on timezonefinder to be built. 

It is important to note that the package will not include numba as numba needs to be packaged in conda-forge. This can be added in the future if someone wants to create the conda-forge numba package and manage the build for Windows/Linux/Max.

**Comment by snowman2** [comment]
Just FYI, I attempted the build without numba and it worked. However, without it spit out:

===== testing package: timezonefinder-1.5.7-py27_0 =====
import: 'timezonefinder'
Traceback (most recent call last):
  File "/staged-recipes/build_artefacts/timezonefinder_1485788146123/test_tmp/run_test.py", line 27, in <module>
    import timezonefinder
  File "/staged-recipes/build_artefacts/timezonefinder_1485788146123/_t_env/lib/python2.7/site-packages/timezonefinder/__init__.py", line 3, in <module>
    from .timezonefinder import TimezoneFinder
  File "/staged-recipes/build_artefacts/timezonefinder_1485788146123/_t_env/lib/python2.7/site-packages/timezonefinder/timezonefinder.py", line 58, in <module>
    from .helpers_numba import coord2int, distance_to_polygon_exact, distance_to_polygon, inside_polygon, all_the_same
  File "/staged-recipes/build_artefacts/timezonefinder_1485788146123/_t_env/lib/python2.7/site-packages/timezonefinder/helpers_numba.py", line 108, in <module>
    @jit('b1(i4,i4,i4[:,:])', nopython=True, cache=True)
  File "/staged-recipes/build_artefacts/timezonefinder_1485788146123/_t_env/lib/python2.7/site-packages/numba/decorators.py", line 151, in jit
    return wrapper(pyfunc)
  File "/staged-recipes/build_artefacts/timezonefinder_1485788146123/_t_env/lib/python2.7/site-packages/numba/decorators.py", line 167, in wrapper
    **dispatcher_args)
  File "/staged-recipes/build_artefacts/timezonefinder_1485788146123/_t_env/lib/python2.7/site-packages/numba/dispatcher.py", line 425, in __init__
    pysig = utils.pysignature(py_func)
  File "/staged-recipes/build_artefacts/timezonefinder_1485788146123/_t_env/lib/python2.7/site-packages/funcsigs/__init__.py", line 59, in signature
    raise TypeError('{0!r} is not a callable object'.format(obj))
TypeError: u'b1(i4,i4,i4[:,:])' is not a callable object
TESTS FAILED: timezonefinder-1.5.7-py27_0


I am not familiar with numba, so I am going to move forward without.

**Comment by MrMinimal64** [comment]
I assume you got this error with Python2.7 and WITH numba (other users reported the same issue), right? Either numba has simply not been properly installed or there seems to be a compatibility issue in that configuration at the moment. Please note that numba itself has some dependencies (also non python if I remember correctly). With Python 3.x and Numba it works for me.

**Comment by snowman2** [comment]
Perfect! I modified it to only include numba with python 3 and it worked.

**Comment by snowman2** [comment]
It is ready: https://github.com/conda-forge/timezonefinder-feedstock
