### ISSUE TITLE
pointer variable not initialised if force_evaluation is False

### ISSUE THREAD

**Issue by logi** [MrMinimal64/timezonefinder#50]
From our unit tests:
```
   troupe.utils.geo_lookup: ERROR: Failed to get timezone for 13,100
   Traceback (most recent call last):
     File "/home/saltmaster/wod.git/troupe/src/utils/geo_lookup.py", line 41, in timezone_at_location
       tz_name = TIMEZONE_FINDER.closest_timezone_at(lat=lat, lng=lon)
     File "/home/saltmaster/conda/envs/troupe/lib/python3.6/site-packages/timezonefinder/functional.py", line 27, in wrapper
       return func(*args, **kwargs)
     File "/home/saltmaster/conda/envs/troupe/lib/python3.6/site-packages/timezonefinder/timezonefinder.py", line 442, in closest_timezone_at
       while pointer < polygons_in_list:
   UnboundLocalError: local variable 'pointer' referenced before assignment
```

Also, it's just super clear from reading the code.

**Comment by MrMinimal64** [comment]
hm thanks. fixing it right now

**Comment by MrMinimal64** [comment]
btw @logi: closest_timezone_at() is not really useful any more with the new data (cf. readme).
