### ISSUE TITLE
Error when querying timezone for some extreme values of latitude, longitude

### ISSUE THREAD

**Issue by ddudnik** [MrMinimal64/timezonefinder#52]
Hi, this might not be super important but for the sake of correctness:

Some of extreme values of latitude/longitude cannot be handled correctly by timezonefinder. For instance, following examples would result in an error instead of returning 'None'.

`python -m timezonefinder.timezonefinder 180.0 0.0`
`python -m timezonefinder.timezonefinder 179.0 -90.0`

Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dudnik/Projects/timezonefinder/timezonefinder/timezonefinder.py", line 587, in <module>
    tz = tf.timezone_at(lng=longitude, lat=latitude)
  File "/home/dudnik/Projects/timezonefinder/timezonefinder/functional.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/dudnik/Projects/timezonefinder/timezonefinder/timezonefinder.py", line 487, in timezone_at
    return timezone_names[unpack(b'<H', self.shortcuts_unique_id.read(2))[0]]
struct.error: unpack requires a buffer of 2 bytes
```

Basically some values of longitude and latitude would cause 'shortcut_id_x' and 'shortcut_id_y' result in a position which is out of bounds of 'shortcuts_unique_id.bin' file.

**Comment by MrMinimal64** [comment]
thanks for pointing that out. i'll have a look into it.
