### ISSUE TITLE
ValueError, coords out of bounds on initial import w/ 3.4.1 and python 2.7

### ISSUE THREAD

**Issue by parente** [MrMinimal64/timezonefinder#70]
If timezonefinder does not support Python 2.7, that's perfectly fine and this issue should be refiled against the conda-forge feedstock so that it only builds python 3.x packages.

```
pparente@vm4-002 ~ ❯❯❯ conda create -n tzfinder 'python=2.7*' 'timezonefinder>=3.4.1'
Solving environment: done

## Package Plan ##

  environment location: /home/pparente/miniconda/envs/tzfinder

  added / updated specs:
    - python=2.7
    - timezonefinder[version='>=3.4.1']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.16.0               |py27_blas_openblashb06ca3d_0         9.1 MB  conda-forge
    openblas-0.3.3             |       ha44fe06_1        13.7 MB  conda-forge
    blas-1.1                   |         openblas           1 KB  conda-forge
    libgfortran-3.0.0          |                1         281 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        23.0 MB

The following NEW packages will be INSTALLED:

    blas:                1.1-openblas                        conda-forge
    ca-certificates:     2018.11.29-ha4d7672_0               conda-forge
    certifi:             2018.11.29-py27_1000                conda-forge
    enum34:              1.1.6-py27_1001                     conda-forge
    funcsigs:            1.0.2-py_3                          conda-forge
    importlib_resources: 1.0.2-py27_1000                     conda-forge
    libffi:              3.2.1-hfc679d8_5                    conda-forge
    libgcc-ng:           7.2.0-hdf63c60_3                    conda-forge
    libgfortran:         3.0.0-1                             conda-forge
    libstdcxx-ng:        7.2.0-hdf63c60_3                    conda-forge
    llvmlite:            0.26.0-py27hd28b015_0               conda-forge
    ncurses:             6.1-hfc679d8_2                      conda-forge
    numba:               0.41.0-py27hf8a1672_0               conda-forge
    numpy:               1.16.0-py27_blas_openblashb06ca3d_0 conda-forge [blas_openblas]
    openblas:            0.3.3-ha44fe06_1                    conda-forge
    openssl:             1.0.2p-h470a237_2                   conda-forge
    pathlib2:            2.3.3-py27_1000                     conda-forge
    pip:                 18.1-py27_1000                      conda-forge
    python:              2.7.15-h33da82c_6                   conda-forge
    readline:            7.0-haf1bffa_1                      conda-forge
    scandir:             1.9.0-py27h470a237_0                conda-forge
    setuptools:          40.6.3-py27_0                       conda-forge
    singledispatch:      3.4.0.3-py27_1000                   conda-forge
    six:                 1.12.0-py27_1000                    conda-forge
    sqlite:              3.26.0-hb1c47c0_0                   conda-forge
    timezonefinder:      3.4.1-py_0                          conda-forge
    tk:                  8.6.9-ha92aebf_0                    conda-forge
    typing:              3.6.6-py27_1000                     conda-forge
    wheel:               0.32.3-py27_0                       conda-forge
    zlib:                1.2.11-h470a237_4                   conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
numpy-1.16.0         | 9.1 MB    | ################################################################################### | 100%
openblas-0.3.3       | 13.7 MB   | ################################################################################### | 100%
blas-1.1             | 1 KB      | ################################################################################### | 100%
libgfortran-3.0.0    | 281 KB    | ################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate tzfinder
#
# To deactivate an active environment, use
#
#     $ conda deactivate

pparente@vm4-002 ~ ❯❯❯ conda activate tzfinder
(tzfinder) pparente@vm4-002 ~ ❯❯❯ python
Python 2.7.15 | packaged by conda-forge | (default, Nov 29 2018, 06:43:57)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import timezonefinder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/timezonefinder/__init__.py", line 3, in <module>
    from .timezonefinder import TimezoneFinder
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/timezonefinder/timezonefinder.py", line 22, in <module>
    from .helpers_numba import coord2int, distance_to_polygon_exact, distance_to_polygon, inside_polygon, \
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/timezonefinder/helpers_numba.py", line 309, in <module>
    @njit(dtype_2float_tuple(f8, f8), cache=True)
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/decorators.py", line 198, in wrapper
    disp.compile(sig)
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/pparente/miniconda/envs/tzfinder/lib/python2.7/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
cannot determine Numba type of <type 'unicode'>

File "miniconda/envs/tzfinder/lib/python2.7/site-packages/timezonefinder/helpers_numba.py", line 312:
def rectify_coordinates(lng, lat):
    <source elided>
    if lng > 180.0 or lng < -180.0 or lat > 90.0 or lat < -90.0:
        raise ValueError('The coordinates should be given in degrees. They are out ouf bounds.')
        ^
```

**Comment by MrMinimal64** [comment]
timezonefinder is normally supporting Python2.7, but Numba compiled code apparently cannot output unicode strings under Python2.7. I fixed this in the new release. Thanks for pointing this out and please notify me in case this error persists.
